services:

  mysql:
    image: mysql:latest
    container_name: g2a-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: g2a
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local

networks:
  local:

#  --> terminal <--
#  docker-compose down
#  docker-compose up --build