package pl.studia.GameKeySite_Project_PSBD.model.enums;

public enum Genre {
    ACTION, ADVENTURE, RPG, JRPG, MMORPG, FPS, TPS, SURVIVAL, HORROR, FIGHTING, PLATFORMER, STRATEGY, MOBA, SIMULATION,
    SPORTS, RACING, SANDBOX, ROUGELIKE, PUZZLE, STEALTH
}

